export default
[
    {
        name: 'Exercise Stress Test',
        diagnosticUrl: 'exercise-stress-test',
        offName: 'EXERCISE STRESS TEST',
        about: 'A cardiac stress test ECG is also known as a stress test, exercise ECG, or treadmill test. A cardiac stress test ECG evaluates how your heart performs and functions during exercise, and is used to assess the general health of your heart. It can also detect poor physical fitness, irregular heartbeats, and coronary artery disease. The test is often performed for people with abnormal heart rhythms, chest pain, or those planning to begin an exercise regimen.',
        warning: 'Do not eat, consume caffeine or alcohol, or smoke in the three hours prior to your cardiac stress test. Inform your doctor if you have taken Viagra in the previous 24 hours. Wear loose fitting clothes for a comfortable, proper procedure.',
        procedure1: 'Your baseline blood pressure and heart rate will be recorded before the test begins. Your doctor will apply some small patches of electrodes to your skin on several areas of your body. Your arm will wear a blood pressure cuff for the duration of the procedure.',
        procedure2: 'You will then exercise on a treadmill or other equipment like a stationary bike, gradually increasing your pace and resistance. Your blood pressure and heart’s electrical activity will be continually recorded throughout the test.',
        procedure3: 'If you have physical limitations that prevent you from exercising on equipment, a stress test is still possible by injecting a chemical that safely raises your heart rate. In either situation, stress tests are generally safe and prompt medical attention is nearby should complications arise. After the test, your doctor will go over the results with you.'
    },
    {
        name: 'Nuclear Stress Test',
        diagnosticUrl: 'nuclear-stress-test',
        offName: 'NUCLEAR STRESS TEST',
        about: '',
        warning: '',
        procedure1: '',
        procedure2: '',
        procedure3: '',
    },
    {
        name: 'Echocardiogram',
        diagnosticUrl: 'echocardiogram',
        offName: 'ECHOCARDIOGRAM',
        about: 'An echocardiogram, also known as a transthoracic echocardiogram, surface echo, or Doppler heart ultrasound, is an ultrasound of the heart. Sound waves provide a real-time image of the beating heart.',
        warning: '',
        procedure1: 'An echocardiogram creates a detailed live picture of the heart that is used to assess heart pumping, evaluate functioning of the heart chambers and valves, and screen for heart murmurs. It is commonly used to evaluate hear functioning in people that have previously had heart attacks, as well as check for heart disease.',
        procedure2: '',
        procedure3: '',
    },
    {
        name: 'Electrocardiogram',
        diagnosticUrl: 'electrocardiogram',
        offName: 'ELECTROCARDIOGRAM',
        about: 'An electrocardiogram measures the electrical activity of the heart and is useful when determining whether or not the heart is beating normally. It is often used for people with suspected heart disease, chest pain, or heart palpitations. An electrocardiogram provides information about the size and location of heart damage, the heart chambers, and the effect of heart regulating medication or a pacemaker.',
        warning: '',
        procedure1: 'Before your procedure, a technician will apply several discs of electrodes to your skin. The electrodes will send information to a recording machine. At several points during the procedure, a technician will ask you to hold your breath or remain motionless. An echocardiogram is a painless, easy procedure. After the recording machine prints your results, the doctor will review them with you.',
        procedure2: '',
        procedure3: '',
    },
    {
        name: 'Vascular Ultrasound',
        diagnosticUrl: 'vascular-ultrasound',
        offName: 'VASCULAR ULTRASOUND',
        about: '',
        warning: '',
        procedure1: '',
        procedure2: '',
        procedure3: '',
    },
    {
        name: 'Holter Monitoring',
        diagnosticUrl: 'holter-monitoring',
        offName: 'VASCULAR ULTRASOUND',
        about: '',
        warning: '',
        procedure1: '',
        procedure2: '',
        procedure3: '',
    },
    {
        name: 'Event Monitoring (30-Day)',
        diagnosticUrl: 'event-monitoring',
        offName: 'EVENT MONITORING',
        about: '',
        warning: '',
        procedure1: '',
        procedure2: '',
        procedure3: '',
    },
    {
        name: 'Peripheral Arterial Disease (PAD) Screening',
        diagnosticUrl: 'pad-screening',
        offName: 'PERIPHERAL ARTERIAL DISEASE SCREENING',
        about: '',
        warning: '',
        procedure1: '',
        procedure2: '',
        procedure3: '',
    },
    {
        name: 'Laboratory / Blood Work',
        diagnosticUrl: '',
        offName: '',
        about: '',
        warning: '',
        procedure1: '',
        procedure2: '',
        procedure3: '',
    },
]