export default 
[
    {
        name: 'Cardiac Catheterization',
        offName: 'CARDIAC CATHETERIZATION',
        serviceUrl: 'cardiac-catheterization',
        intro: 'A cardiac catheterization is most often performed at a hospital. Do not eat or drink for six to eight hours prior to your procedure. After receiving a mild sedative, you will remain awake during the procedure. The area of catheter insertion will be numbed with a local anesthetic.',
        pOne: 'Cardiac catheterization is a procedure used in diagnoses or treatment in which a thin, flexible tube is advanced into the heart. Cardiac catheterization provides useful information about the heart’s functioning. Performed with an imaging technique called fluoroscopy, cardiac catheterization records pictures of the heart while the heart beats. The resulting pictures can help identify heart disease, blood clots, heart enlargement, heart defects, aneurysm, valve problems, or coronary artery blockage. Cardiac catheterization can be used as a treatment procedure to repair open arteries, open valves, and heart defects.',
        pTwo: 'A cardiac catheterization is most often performed at a hospital. Do not eat or drink for six to eight hours prior to your procedure. After receiving a mild sedative, you will remain awake during the procedure. The area of catheter insertion will be numbed with a local anesthetic. The catheter, a long, flexible tube, may be inserted into an artery in the groin or arm area. Remain still during the procedure. A dye inserted by your doctor will allow your heart and blood vessels to be seen on an X-ray video. After removing the catheter and completing the procedure, your doctor will go over your results with you.',
        pThree: 'Cardiac imaging is a branch of radiology that specializes in using technology to allow detailed observation of the heart and blood vessels without open surgery. There are various types of cardiac imaging that allow doctors to check for heart problems, monitor heart functioning, and diagnose heart disorders. Stroke and other conditions can be evaluated by imaging blood vessels in the brain.',
        pFour: 'Computerized Axial Scanning, which helps determine the impact of a stroke by imaging the brain’s blood vessels.',
        pFive: 'Coronary Artery Scan or Cardiac Computed Tomography (CT), which helps doctors check for disease or blockages by producing cross-sectional pictures of the heart and its blood vessels.',
        pSix: 'Cardiac Positron Emission Tomography (PET), which evaluates heart tissue function using radionuclide tracers with enough detail to identify injured but living heart muscle.',
        pSeven: 'Digital Cardiac Angiography (DCA), which detects blockages by using a contrast dye to emphasize the major blood vessels in images of the heart and brain.',
        pEight: 'Electron-Beam Computed Tomography (EBCT), which is used to detect calcification by taking very fast images that help assess muscle mass, heart chamber volume, bypass grafts, heart lesions, and pressure. EBCT results can gauge the need for coronary bypass surgery or risk of heart attack.',
        pNine: 'Magnetic Resonance Imaging (MRI), which produces very detailed images of the heart that help assess disorders, defects, and damage from a heart attack. Doctors can evaluate damage caused by a stroke through an MRI of the brain.',
        pTen: 'Radionuclide Imaging, which indicates areas of brain damage and shows brain functioning through injected radioactive substance imaging. Radionuclide imaging can locate the damaged areas caused by a heart attack.',
        pEleven: 'Single Photon Emission Controlled Tomography (SPECT), which produces cross-sectional images of the heart through use of injected radioactive tracers and imaging. SPECT can locate heart disease, coronary artery disease, heart muscle blood flow issues, and determine the severity of heart abnormalities.',
    },
    {
        name: 'Coronary Artery Interventions',
        offName: 'CORONARY ARTERY INTERVENTIONS',
        serviceUrl: 'coronary-artery-interventions',
        intro: 'The arteries of the heart become narrowed or even blocked due to plaque, a sticky material, if you suffer from coronary artery disease. Angioplasty is a medical procedure that can restore blood flow throughout the artery.',
        pOne: 'Doctors may recommend angioplasty in order to minimize the damage to heart muscle after a heart attack and to decrease chest pain that results from reduced blood flow to the heart. In certain cases, angioplasty is a non-surgical method of successfully treating heart disease.',
        pTwo: 'The procedure is performed in a hospital. The doctor will thread a thin, narrow tube via a blood vessel in the groin or arm all the way to the artery in question. A very small balloon is attached to the end of the thin tube. The doctor will inflate this tiny balloon once the tube is place, thus pushing the plaque outward and compressing it against the artery wall. By doing this, your artery widens and blood flow is restored. Angioplasties are relatively easy procedures and most patients return home the day after, and return to work within one week.',
        opOne: 'CORONARY STENTING',
        pThree: 'To prevent blood clots and stroke, your doctor may prescribe some medications. An interventional technique, carotid angioplasty involves placing a catheter inside the artery in order to hold open a narrowed area. Alternatively, your doctor may insert a stent.',
        pFour: 'There are several interventional procedures that may help treat coronary artery disease, including coronary angioplasty, athrectomy, stenting, and brachytherapy. A coronary angioplasty opens blocked coronary arteries. An inserted stent keeps a coronary artery open.',
        pFive: 'A stent is a small tube made of metal mesh that behaves like a scaffold to help support the interior of your coronary artery. Your doctor will use a balloon catheter put over a guide wire to insert the stent into the narrowed or blocked coronary artery. The balloon tip will be inflated once it is in place, and the stent will inflate to the artery’s size, holding it open. After deflating and removing the balloon, the stent permanently remains in place.',
        pSix: 'The artery will heal around the stent over the course of several weeks. Sometimes, stents will contain medicine and have been designed to reduce the risk of restenosis, which is the risk of reblockage.',
    },
    {
        name: 'Pacemaker Implantation',
        offName: 'PACEMAKER IMPLANTATION',
        serviceUrl: 'pacemaker-implantation',
        intro: 'Often referred to as an integral part of cardiac resynchronization therapy, a pacemaker is a small device that is implanted near the heart to help control the heartbeat. Patients may require pacemakers for many reasons, but arrhythmias are the most common reason for pacemaker implantation.',
        pOne: 'Heart muscle may suffer damage after a heart attack. Otherwise, normal aging of the heart can result in a disrupted heart rate, gradually slowing to beat at an inadequate speed. In other cases, some medications can negatively affect the heart rate. In some cases, genetic conditions are the root of an abnormal heart rate. No matter what causes an abnormal heart rate, a pacemaker is often the possible cure.',
        pTwo: 'A pacemaker regularly sends electrical pulses to your heart to keep it beating at a regular, steady rate. Having a pacemaker fitted to regular your heartbeat can greatly benefit your qualify of life, and can even be a lifesaver. The pacemaker contains a battery that may last up to a decade, a pulse generator, and a very small computer circuit that turns battery energy into electrical impulses that then flow through wires to your heart, making it contract.',
        pThree: 'Minor surgery is needed to implant a pacemaker into the chest, and the procedure is a fairly straightforward process. The implantation area will receive local anesthetic, leaving you awake during the process. The generator is usually placed beneath the skin near the left collarbone. It is then attached to a wire that connects to the heart through a blood vessel.',
        pFour: 'The procedure is fairly short, taking only about an hour. The majority of patients recover quickly enough to be discharged from the hospital a mere day after the procedure.',
    },
    {
        name: 'Implantable Arrhythmia Monitoring',
        offName: 'IMPLANTABLE ARRHYTHMIA MONITORING',
        serviceUrl: 'implantable-arrhythmia-monitoring',
        intro: 'Cardiac arrhythmias, also known as heart arrhythmias, are the abnormal and irregular heart rhythms that occur when the heart beats too slowly, too quickly, or erratically. Anywhere along the heart chambers’ nerve signal pathway, there may be a disturbance, causing a heart arrhythmia.',
        pOne: 'Heart arrhythmias come in many forms and levels of severity; the most serious cases can result in a heart attack or even a sudden death. Treatments include medications, pacemakers, electrophysiologic ablations, and implantable cardioverter-defibrillators.',
        pTwo: 'Tinier than a pacemaker, an implantable arrhythmia monitoring device allows greater comfort for the patient. The device could continuously monitor and track the patient’s ECG, classify the heart rhythm, and perform continuous, long-term analysis of the heart rate. Implantable arrhythmia monitoring devices would provide for real time and long-term analysis of the heart rate, a boon to people at risk of arrhythmic events.',
    }
]